using Renamer.Execution;

namespace Renamer.Tests.Contracts;

/// <summary>
/// Pins the stored form of a journal row's sidecar delta: what the forward path writes, what an undo
/// reads back, and what happens to a value this code did not write. No store, no database context, no
/// filesystem — the module under test touches none, which is the whole reason this suite needs no
/// setup, no doubles and no running service.
/// </summary>
/// <remarks>
/// PLACEMENT IS LOAD-BEARING, and this file is deliberately NOT under <c>Execution/</c>. The
/// cove-absent continuous-integration leg removes the <c>Execution</c>, <c>Events</c>,
/// <c>Concurrency</c> and <c>Preview</c> folders wholesale, so a pure suite placed beside the code it
/// covers would silently stop running exactly on the leg where this repository's coverage is
/// thinnest. <c>Contracts/</c> is covered by no <c>Compile Remove</c> entry. Do not "tidy" this file
/// next to <c>RevertDelta.cs</c>'s other tests.
/// <para>
/// Every fixture below is a hand-written literal, transcribed from the shape the forward path
/// produces — never generated by serializing and then parsing, which would only prove the code agrees
/// with itself forever. Both directions are checked against the SAME transcribed constant, so a change
/// to the format has to be made here deliberately rather than absorbed silently.
/// </para>
/// </remarks>
[Trait("Tier", "L0")]
public sealed class RevertDeltaLogicTests
{
    /// <summary>
    /// A rename that moved a tracked caption and a configured neighbour, then rewrote the caption's
    /// stored filename — transcribed by hand from the records the executor's capture point produces.
    /// </summary>
    private const string TwoSidecarsAndACaption =
        "s|/media/in/clip.en.vtt|/media/out/My Film.en.vtt\n"
        + "s|/media/in/clip.srt|/media/out/My Film.srt\n"
        + "c|4218|clip.en.vtt";

    [Fact]
    public void TheStoredForm_ReadsBackAsTheMovesAndTheCaptionItNames()
    {
        Assert.True(RevertDelta.TryParse(TwoSidecarsAndACaption, out var delta));

        Assert.Collection(
            delta.Sidecars,
            s =>
            {
                Assert.Equal("/media/in/clip.en.vtt", s.FromPath);
                Assert.Equal("/media/out/My Film.en.vtt", s.ToPath);
            },
            s =>
            {
                Assert.Equal("/media/in/clip.srt", s.FromPath);
                Assert.Equal("/media/out/My Film.srt", s.ToPath);
            });

        var caption = Assert.Single(delta.Captions);
        Assert.Equal(4218, caption.CaptionId);
        // The ORIGINAL stored filename, which is the value undo writes back — not the renamed one.
        Assert.Equal("clip.en.vtt", caption.OriginalFilename);
    }

    [Fact]
    public void TheSameDelta_WritesBackToTheSameStoredForm()
    {
        var delta = new RevertDelta(
            [
                new RevertSidecarDelta("/media/in/clip.en.vtt", "/media/out/My Film.en.vtt"),
                new RevertSidecarDelta("/media/in/clip.srt", "/media/out/My Film.srt"),
            ],
            [new RevertCaptionDelta(4218, "clip.en.vtt")]);

        Assert.Equal(TwoSidecarsAndACaption, delta.Serialize());
    }

    [Fact]
    public void ARenameThatMovedNothing_IsTheEmptyMarkerTheColumnAlreadyDefaultsTo()
    {
        // Same bytes for "no sidecars" and for "written before deltas existed" — one state, not two.
        Assert.Equal("", RevertDelta.Empty.Serialize());
        Assert.Equal("", new RevertDelta([], []).Serialize());

        Assert.False(RevertDelta.TryParse("", out var fromEmpty));
        Assert.Empty(fromEmpty.Sidecars);
        Assert.Empty(fromEmpty.Captions);

        Assert.False(RevertDelta.TryParse(null, out var fromNull));
        Assert.Empty(fromNull.Sidecars);
        Assert.Empty(fromNull.Captions);
    }

    [Fact]
    public void APathHoldingTheFormatsOwnSeparators_SurvivesBothDirections()
    {
        // A pipe, a backslash and a newline are all legal in a filename on the platforms Cove runs, so
        // an unescaped one would split a single path across two fields — and undo would then move a
        // file to a path that never existed.
        const string stored = @"s|/media/a\pb/c\\d/e\nf.srt|/media/out/My Film.srt";

        Assert.True(RevertDelta.TryParse(stored, out var delta));
        var sidecar = Assert.Single(delta.Sidecars);
        Assert.Equal("/media/a|b/c\\d/e\nf.srt", sidecar.FromPath);
        Assert.Equal("/media/out/My Film.srt", sidecar.ToPath);

        Assert.Equal(stored, new RevertDelta([sidecar], []).Serialize());
    }

    [Fact]
    public void ANonAsciiPath_SurvivesBothDirections()
    {
        const string stored = "s|/média/Amélie — 2001/clip.srt|/média/Amélie — 2001/Amélie.srt";

        Assert.True(RevertDelta.TryParse(stored, out var delta));
        var sidecar = Assert.Single(delta.Sidecars);
        Assert.Equal("/média/Amélie — 2001/clip.srt", sidecar.FromPath);
        Assert.Equal("/média/Amélie — 2001/Amélie.srt", sidecar.ToPath);

        Assert.Equal(stored, new RevertDelta([sidecar], []).Serialize());
    }

    [Fact]
    public void AValueFromAnUnknownVariant_YieldsWhatItCanAndDropsTheRest()
    {
        // Hand-written as a future or corrupted writer might leave it: a record shape this code does
        // not know, a truncated one, a caption whose id is not a number, and a good record carrying an
        // extra trailing field. A row that cannot be read in full must still restore the file it names.
        const string mixed =
            "x|something|this code has never seen\n"
            + "s|/media/in/only-one-field\n"
            + "c|not-a-number|clip.en.vtt\n"
            + "s|/media/in/clip.srt|/media/out/My Film.srt|trailing-field-from-a-later-version\n"
            + "c|77|clip.srt";

        Assert.True(RevertDelta.TryParse(mixed, out var delta));

        var sidecar = Assert.Single(delta.Sidecars);
        Assert.Equal("/media/in/clip.srt", sidecar.FromPath);
        Assert.Equal("/media/out/My Film.srt", sidecar.ToPath);

        var caption = Assert.Single(delta.Captions);
        Assert.Equal(77, caption.CaptionId);
        Assert.Equal("clip.srt", caption.OriginalFilename);
    }

    [Fact]
    public void AValueThisCodeCannotReadAtAll_IsEmptyRatherThanAThrow()
    {
        const string unreadable = "x|nothing\nhere|is|readable-because-the-tag-is-unknown";

        Assert.False(RevertDelta.TryParse(unreadable, out var delta));
        Assert.Empty(delta.Sidecars);
        Assert.Empty(delta.Captions);
    }

    [Fact]
    public void AnUnknownEscapeAndATrailingLoneBackslash_DegradeInsteadOfThrowing()
    {
        // \q names no escape this code defines, so the escaped character survives and the backslash is
        // dropped — "cl\qip" reads back as "clqip". A lone trailing backslash names nothing at all and
        // goes away. Neither throws, which is what keeps a row with a damaged delta restorable.
        Assert.True(RevertDelta.TryParse(@"s|/media/in/cl\qip.srt|/media/out/film.srt\", out var delta));

        var sidecar = Assert.Single(delta.Sidecars);
        Assert.Equal("/media/in/clqip.srt", sidecar.FromPath);
        Assert.Equal("/media/out/film.srt", sidecar.ToPath);
    }
}
