using Microsoft.Extensions.Logging;
using Renamer.Planner;

namespace Renamer;

// The renamer slice's log messages. Every method here is generated by the [LoggerMessage] source
// generator and writes through the partial class's _log field, so a call site carries no boxing and
// evaluates no argument when the level is disabled. Renames and moves change files on disk, so a
// batch, an undo and an auto-rename each record the old and new path, skip reasons and a summary.
public sealed partial class Renamer
{
    [LoggerMessage(
        EventId = 1000, Level = LogLevel.Information,
        Message = "[Renamer] batch {RunId} ({Kind}) started: {Count} item(s)")]
    private partial void LogBatchStarted(string runId, RenamerFileKind kind, int count);

    [LoggerMessage(
        EventId = 1001, Level = LogLevel.Information,
        Message = "[Renamer] batch {RunId}: {Kind} id={EntityId} {Status} '{Old}' -> '{New}'")]
    private partial void LogItemRenamed(
        string runId, RenamerFileKind kind, int entityId, RenamerStatus status, string old, string @new);

    [LoggerMessage(
        EventId = 1002, Level = LogLevel.Information,
        Message = "[Renamer] batch {RunId}: {Kind} id={EntityId} skipped ({Status}): {Reason}")]
    private partial void LogItemSkipped(
        string runId, RenamerFileKind kind, int entityId, RenamerStatus status, string reason);

    // A renamed item can carry a warning for work that failed after the save committed (an unwritten
    // undo row, an unpublished event, a source folder left behind). Without this the rename line reports
    // a clean success and the warning reaches nothing.
    [LoggerMessage(
        EventId = 1014, Level = LogLevel.Warning,
        Message = "[Renamer] batch {RunId}: {Kind} id={EntityId} renamed WITH a warning: {Reason}")]
    private partial void LogItemRenamedWithWarning(string runId, RenamerFileKind kind, int entityId, string reason);

    [LoggerMessage(
        EventId = 1003, Level = LogLevel.Warning,
        Message = "[Renamer] batch {RunId}: {Kind} id={EntityId} FAILED '{Old}' -> '{New}': {Reason}")]
    private partial void LogItemFailed(
        string runId, RenamerFileKind kind, int entityId, string old, string @new, string reason);

    [LoggerMessage(
        EventId = 1004, Level = LogLevel.Information,
        Message = "[Renamer] batch {RunId} done: {Renamed} renamed, {Skipped} skipped, {Failed} failed")]
    private partial void LogBatchDone(string runId, int renamed, int skipped, int failed);

    // These trace a batch's planning in Cove's log.

    [LoggerMessage(
        EventId = 1005, Level = LogLevel.Information,
        Message = "[Renamer] batch {RunId} ({Kind}): planning {Count} item(s)…")]
    private partial void LogPlanningStarted(string runId, RenamerFileKind kind, int count);

    [LoggerMessage(
        EventId = 1006, Level = LogLevel.Information,
        Message = "[Renamer] batch {RunId}: planning {Index}/{Count} id={EntityId}: {ActingFiles} file(s) will act")]
    private partial void LogItemPlanned(string runId, int index, int count, int entityId, int actingFiles);

    [LoggerMessage(
        EventId = 1007, Level = LogLevel.Information,
        Message = "[Renamer] batch {RunId}: planning complete: {Acting} file(s) will act across {Planned} item(s)")]
    private partial void LogPlanningDone(string runId, int acting, int planned);

    // The one trace of a refused source-path claim: the rename cannot tell which of the rows owns the
    // file, so it moves none of them and names the path a maintainer has to reconcile.
    [LoggerMessage(
        EventId = 1009, Level = LogLevel.Warning,
        Message = "[Renamer] batch {RunId}: {Claims} file rows name the source path '{Path}', so none of them renamed")]
    private partial void LogContestedSourcePath(string runId, string path, int claims);

    // Logged before a move runs. A cross-volume move is a full copy, verify and delete that can take
    // many seconds for a large file, while a same-volume rename is near-instant, so the CrossVolume
    // flag lets a reader tell a slow copy from a quick rename.
    [LoggerMessage(
        EventId = 1008, Level = LogLevel.Information,
        Message = "[Renamer] batch {RunId}: {Done}/{Total} starting {Kind} id={EntityId} (crossVolume={CrossVolume}, {SizeMb} MB) '{Old}'")]
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Major Code Smell", "S107:Methods should not have too many parameters",
        Justification = "Each parameter is one placeholder of the structured log message.")]
    private partial void LogItemStarting(
        string runId, int done, int total, RenamerFileKind kind, int entityId, bool crossVolume, long sizeMb, string old);

    // A whole-library job fans out one batch per kind, and the inner per-batch lines alone do not say
    // which kind is running or how large it is.

    [LoggerMessage(
        EventId = 1040, Level = LogLevel.Information,
        Message = "[Renamer] library rename: {Kind}: {Count} item(s) to plan")]
    private partial void LogLibraryKind(RenamerFileKind kind, int count);

    // These trace the whole-library dry run's planning in Cove's log.

    [LoggerMessage(
        EventId = 1050, Level = LogLevel.Information,
        Message = "[Renamer] scan library: {Total} item(s) across {Kinds} kind(s) to plan")]
    private partial void LogScanStarted(int total, int kinds);

    [LoggerMessage(
        EventId = 1051, Level = LogLevel.Information,
        Message = "[Renamer] scan library: planned {Done}/{Total} ({Kind} id={EntityId})")]
    private partial void LogScanItemPlanned(int done, int total, RenamerFileKind kind, int entityId);

    [LoggerMessage(
        EventId = 1052, Level = LogLevel.Information,
        Message = "[Renamer] scan library: complete: {Files} file(s) planned from {Total} item(s)")]
    private partial void LogScanDone(int files, int total);

    [LoggerMessage(
        EventId = 1053, Level = LogLevel.Warning,
        Message = "[Renamer] could not delete the legacy per-file scan result; the settings page may stay unreadable")]
    private partial void LogLegacyScanPurgeFailed(Exception ex);

    [LoggerMessage(
        EventId = 1054, Level = LogLevel.Warning,
        Message = "[Renamer] could not migrate or clear the legacy stored undo journal; the settings page may stay unreadable until the next load retries")]
    private partial void LogJournalBlobMigrationFailed(Exception ex);

    // The legacy journal migration deletes its own source, so this line is the only lasting trace that
    // it ran and what it moved. It carries a count and nothing else, because the value it read is a
    // list of the user's file paths.
    [LoggerMessage(
        EventId = 1064, Level = LogLevel.Information,
        Message = "[Renamer] undo journal migration: moved {Rows} row(s) out of the legacy stored journal and deleted both legacy keys")]
    private partial void LogJournalBlobMigrated(int rows);

    [LoggerMessage(
        EventId = 1066, Level = LogLevel.Warning,
        Message = "[Renamer] could not convert the stored options to stable entity ids; the settings page may stay unreadable until the next load retries")]
    private partial void LogOptionsMigrationFailed(Exception ex);

    // The deferral is silent to the user, because the panel keeps working from defaults, so this line
    // is the only place the wait is visible and it has to name what it waits for.
    [LoggerMessage(
        EventId = 1067, Level = LogLevel.Information,
        Message = "[Renamer] options conversion deferred: {Tags} tag and {Performers} performer name(s) are still stored, but their table holds no rows yet; retrying on the next load")]
    private partial void LogOptionsMigrationDeferred(int tags, int performers);

    // A dropped rule is configuration the user wrote and will not get back, so the name is logged even
    // though it is user data: without it they cannot tell which rule stopped applying.
    [LoggerMessage(
        EventId = 1068, Level = LogLevel.Warning,
        Message = "[Renamer] options conversion: the rule for '{Name}' was dropped because no entity of that name exists any more")]
    private partial void LogOptionsRuleDropped(string name);

    [LoggerMessage(
        EventId = 1069, Level = LogLevel.Warning,
        Message = "[Renamer] options conversion: '{Name}' matched {AlsoMatched} further entit(ies) differing only by case; the rule now applies to id {MatchedId} alone")]
    private partial void LogOptionsRuleCaseCollapsed(string name, int matchedId, int alsoMatched);

    [LoggerMessage(
        EventId = 1070, Level = LogLevel.Warning,
        Message = "[Renamer] options conversion: the destination for '{Key}' was discarded because it resolves to id {Id}, already routed by '{ClaimedBy}'")]
    private partial void LogOptionsDestinationDiscarded(string key, int id, string claimedBy);

    // The wait is silent to the user, so this line is the only place it is visible, and it has to say
    // what it is waiting for.
    [LoggerMessage(
        EventId = 1071, Level = LogLevel.Information,
        Message = "[Renamer] options conversion deferred: the stored destination rules must be placed under Cove's library paths and the host supplied none; retrying on the next load")]
    private partial void LogOptionsDestinationMigrationDeferred();

    [LoggerMessage(
        EventId = 1072, Level = LogLevel.Information,
        Message = "[Renamer] options conversion: {Rule} moved from '{From}' to library path '{ToRoot}' plus template '{ToTemplate}'")]
    private partial void LogOptionsDestinationRewritten(string rule, string from, string toRoot, string toTemplate);

    // A dropped rule is configuration the user wrote and will not get back, so the stored path is logged
    // even though it is user data: without it they cannot tell which rule stopped applying.
    [LoggerMessage(
        EventId = 1073, Level = LogLevel.Warning,
        Message = "[Renamer] options conversion: {Rule} was dropped because its destination '{Stored}' lies under no Cove library path; its items follow the default destination from now on")]
    private partial void LogOptionsDestinationDropped(string rule, string stored);

    // The library anchor is unavailable for the whole load, so every destination measured from a file's
    // own library path plans as SkipUnanchored until the host supplies its configuration.
    [LoggerMessage(
        EventId = 1074, Level = LogLevel.Warning,
        Message = "[Renamer] the host supplied no Cove configuration; destinations measured from a file's own library path cannot be resolved")]
    private partial void LogNoCoveConfiguration();

    // The extension is about to refuse to load. The throw that follows reaches the host as a disable
    // with an exception; this line is what names the table in the log the operator is already reading.
    [LoggerMessage(
        EventId = 1063, Level = LogLevel.Error,
        Message = "[Renamer] the undo journal table '{Table}' cannot be read; refusing to load rather than rename unjournalled")]
    private partial void LogJournalUnreachable(Exception ex, string table);

    // A sidecar that could not go back leaves its entry restored, so no counted bucket records it.
    // Without this line the user would find a subtitle stranded under the renamed name with nothing
    // saying why.
    [LoggerMessage(
        EventId = 1065, Level = LogLevel.Warning,
        Message = "[Renamer] undo {RunId}: file id={FileId} restored, but a companion file could not be: {Detail}")]
    private partial void LogUndoSidecarStranded(string runId, int fileId, string detail);

    [LoggerMessage(
        EventId = 1010, Level = LogLevel.Information,
        Message = "[Renamer] undo {RunId}: {Kind} id={EntityId} restored to '{Old}'")]
    private partial void LogUndoRestored(string runId, RenamerFileKind kind, int entityId, string old);

    [LoggerMessage(
        EventId = 1011, Level = LogLevel.Information,
        Message = "[Renamer] undo {RunId}: file id={FileId} skipped: {Reason}")]
    private partial void LogUndoSkipped(string runId, int fileId, string reason);

    [LoggerMessage(
        EventId = 1012, Level = LogLevel.Warning,
        Message = "[Renamer] undo {RunId}: file id={FileId} FAILED: {Reason}")]
    private partial void LogUndoFailed(string runId, int fileId, string reason);

    [LoggerMessage(
        EventId = 1013, Level = LogLevel.Information,
        Message = "[Renamer] undo {RunId} done: {Undone} restored, {Skipped} skipped, {Failed} failed")]
    private partial void LogUndoDone(string runId, int undone, int skipped, int failed);

    [LoggerMessage(
        EventId = 1020, Level = LogLevel.Information,
        Message = "[Renamer] auto-renamer: {Kind} id={EntityId} {Status} '{Old}' -> '{New}'")]
    private partial void LogAutoRenamed(
        RenamerFileKind kind, int entityId, RenamerStatus status, string old, string @new);

    [LoggerMessage(
        EventId = 1023, Level = LogLevel.Warning,
        Message = "[Renamer] auto-renamer: {Kind} id={EntityId} renamed WITH a warning: {Reason}")]
    private partial void LogAutoRenamedWithWarning(RenamerFileKind kind, int entityId, string reason);

    [LoggerMessage(
        EventId = 1021, Level = LogLevel.Warning,
        Message = "[Renamer] auto-renamer: {Kind} id={EntityId} FAILED '{Old}' -> '{New}': {Reason}")]
    private partial void LogAutoRenamerFailed(
        RenamerFileKind kind, int entityId, string old, string @new, string reason);

    [LoggerMessage(
        EventId = 1022, Level = LogLevel.Error,
        Message = "[Renamer] auto-renamer failed for {Kind} id={EntityId}")]
    private partial void LogAutoRenamerError(Exception ex, RenamerFileKind kind, int entityId);

    [LoggerMessage(
        EventId = 1030, Level = LogLevel.Warning,
        Message = "[Renamer] routing: skipped invalid source-path regex '{Pattern}': {Reason}")]
    private partial void LogInvalidRouteRegex(string pattern, string reason);

    [LoggerMessage(
        EventId = 1075, Level = LogLevel.Warning,
        Message = "[Renamer] library rename {RunId}: completed, but its counts could not be stored")]
    private partial void LogLibraryRenameSummaryNotStored(Exception ex, string runId);
}
