import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Docusaurus generates a sidebar from the whole docs/ folder structure —
  // adding a new docs/extensions/<id>/ folder needs no edit here (DOCS-03 folder-drop).
  docsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
