import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Sidebar for the extension-owned Renamer docs instance (source: ../extensions/Renamer/docs).
// Autogenerated from that folder — dropping a new page in needs no edit here.
const sidebars: SidebarsConfig = {
  renamerSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
