import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

// Sidebar for the extension-owned Whisparr Sync docs instance (source: ../extensions/WhisparrSync/docs).
// Autogenerated from that folder, so dropping a new page in needs no edit here.
const sidebars: SidebarsConfig = {
  whisparrSyncSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
